// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TileHandle : RemoteTableHandle<EventContext, Tile>
        {
            protected override string RemoteTableName => "tile";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Tile row) => row.EntityId;

                public EntityIdUniqueIndex(TileHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal TileHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(Tile row) => row.EntityId;
        }

        public readonly TileHandle Tile;
    }
}
